# Team Baseline - Average

This baseline model computes the average number of points of the previous N years and use it as a prediction to the N+1 year.

In [1]:
# Imports

import pandas as pd
import numpy as np
from torch import nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from team_dataloader import *

In [2]:
dataset = get_team_dataset()
print(len(dataset))
team_data_loader = DataLoader(dataset=dataset, batch_size=1) # Batch size of 1 to load one data element at a time


637


In [3]:
print(dataset.__getitem__(1))
print(len(dataset.__getitem__(0)))
print("Features")
print(dataset.__getitem__(1)[0])
print(dataset.__getitem__(1)[0].shape)
print("Target")
print(dataset.__getitem__(1)[1])
print(dataset.__getitem__(1)[1].shape)

# Compare to true data
print("True Target")
print(dataset.dataset_with_names[1][1])

# Mean accross columns
x = dataset.__getitem__(1)[0]
print(torch.mean(x, dim=0))

(tensor([[0.2200, 2.3900, 4.7300],
        [0.2400, 2.4400, 3.6300],
        [0.2500, 2.3300, 3.5500],
        [0.4700, 2.7600, 2.8500],
        [0.5060, 2.3500, 2.4400]]), tensor([0.6280, 2.9100, 2.1800]))
2
Features
tensor([[0.2200, 2.3900, 4.7300],
        [0.2400, 2.4400, 3.6300],
        [0.2500, 2.3300, 3.5500],
        [0.4700, 2.7600, 2.8500],
        [0.5060, 2.3500, 2.4400]])
torch.Size([5, 3])
Target
tensor([0.6280, 2.9100, 2.1800])
torch.Size([3])
True Target
           team name   PTS%  GF/G  GA/G  Season
220  Ottawa Senators  0.628  2.91  2.18    1999
tensor([0.3372, 2.4540, 3.4400])


In [6]:
# Get predictions
predictions = []
targets = []


for step, (x,y) in enumerate(team_data_loader):
    predictions.append(torch.mean(x, dim=1))
    targets.append(y)

predictions = torch.stack(predictions)
targets = torch.stack(targets)

print(predictions)
print(targets)

[tensor([[0.2646, 2.4640, 3.8920]]), tensor([[0.3372, 2.4540, 3.4400]]), tensor([[0.4188, 2.5580, 2.9300]]), tensor([[0.4866, 2.6660, 2.7160]]), tensor([[0.5696, 2.8680, 2.5060]]), tensor([[0.5902, 2.9080, 2.4440]]), tensor([[0.6268, 3.0800, 2.4000]]), tensor([[0.5962, 3.1440, 2.7480]]), tensor([[0.5486, 2.8480, 2.8460]]), tensor([[0.5328, 2.7420, 2.8960]]), tensor([[0.5348, 2.5780, 2.7220]]), tensor([[0.5410, 2.6160, 2.7880]]), tensor([[0.5472, 2.6460, 2.7280]]), tensor([[0.5606, 2.7420, 2.7180]]), tensor([[0.5680, 2.6520, 2.6540]]), tensor([[0.5332, 2.7200, 2.9300]]), tensor([[0.5038, 2.7520, 3.0340]]), tensor([[0.4704, 2.7220, 3.1960]]), tensor([[0.4578, 2.7160, 3.2840]]), tensor([[0.4272, 2.7600, 3.4160]]), tensor([[0.4502, 2.8580, 3.3820]]), tensor([[0.4686, 3.4580, 3.5300]]), tensor([[0.4504, 3.2820, 3.4680]]), tensor([[0.4412, 3.2820, 3.5100]]), tensor([[0.4278, 3.1400, 3.3720]]), tensor([[0.4108, 2.8600, 3.2120]]), tensor([[0.3816, 2.6620, 3.1800]]), tensor([[0.3794, 2.6100, 3.

In [7]:
# Define loss
def RMSELoss(yhat, y):
    return torch.sqrt(torch.mean((yhat-y)**2))

In [9]:
# Calculate the loss over all samples
print(predictions)

loss = RMSELoss(predictions, targets)

print(loss)

tensor([[[0.2646, 2.4640, 3.8920]],

        [[0.3372, 2.4540, 3.4400]],

        [[0.4188, 2.5580, 2.9300]],

        ...,

        [[0.5670, 2.5880, 2.6440]],

        [[0.5720, 2.5820, 2.6160]],

        [[0.5144, 2.9300, 3.1840]]])
tensor(0.3085)
